### ISSUE TITLE
Missing "how to use"

### ISSUE THREAD

**Issue by robertontiu** [Calendart/CalendArt#11]
Hey, 

I'm interested in using CalendArt in one of my projects but the documentation really lacks the basic "how to use" information. Could you please give me a brief example ? I'm planning to use the library with Laravel.

**Comment by Taluu** [comment]
Hey there,

Indeed, the most important part in the readme (at least...) is missing. the thing is, the `calendart/calendart` package is really the interface for the google and office adapters... So I think I'm gonna put the examples in the respective repositories, because in here, it doesn't have any value whatsoever imo.

To avoid you to wait for a possible update (can't really do anything else currently, maybe in a week or two though), here is a short example for google (office works approximately the same way) :

``` php
<?php
use CalendArt\Adapter\Google\GoogleAdapter;

// how you retrieve the oauth token is at your discretion
$token = 'my-oauth-token';

$calendart = new GoogleAdapter($token);

$calendar = $calendart->getCalendarApi()->get('clavie.b@gmail.com');
$events = $calendart->getEventApi($calendar)->getList($calendar);
```

This is really the basic usage of the lib. In the case of google adapter, you can filter events etc, but it is kind of a mess (and an undocumented one...). I'll need to sort it out asap, I guess (unless @krichprollsch wants to do it, but I think I know what he'll say :p)...

Thanks for your interest :}
